project:
  type: website
  output-dir: docs
  
website:
  title: "Bo Hu"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: posts/

format:
  html:
    html-math-method: mathjax
    theme:
      - darkly
    toc: true
    css: styles.css
