---
title: "Welcome!"
about: 
  id: hero-heading
  template: solana
  links:
    - icon: github
      text: Github
      href: https://github.com/aloejhb
---
:::{#hero-heading}
Hi, this is Bo.
I enjoyed learning about biology since high school. Afterwards, I went to Beijing Normal University, majoring in Biological Sciences. During this time, I was amazed by the diversity and intelligence of the species on our planet, and yet I still felt unsatisfied: reciting knowledge from textbooks was not enough fun. There must be some logic underlying the seemingly chaotic biological phenomena. That was the motivation for me to continue studying Systems Biology at Heidelberg University, where I learned how to combine mathematical modeling with experiments to understand complex signaling networks in organisms.

One of the networks that really fascinated me was the one in our brain. Luckily, I was able to do my PhD with Rainer W. Friedrich, who gave me invaluable guidance in navigating the landscape of neuroscience. During this time, Nesibe Z. Temiz and I investigated how the olfactory system in zebrafish learns to represent and distinguish different odors. I will always remember the excitement when I first saw calcium signals in pDp on the two-photon setup.

Then I decided to continue investigating how learning and memory work in the brain. Currently, I am working with my cool supervisor Chun Xu at CEBSIT in Shanghai as a postdoc. Here, we are working to better understand plasticity during context-dependent spatial navigation in the hippocampus.

This site is also my external hippocampus, where I record my thoughts on neuroscience. In this way, I can fight against memory loss both through my research and for my own memory loss through writing.
:::