---
title: "Neural manifold beyond a data analysis tool"
date: 2025-05-18
categories: [modeling]
format: html
---
The concept of neural manifold has been introduced for analysis of large scale recordings of neuronal activities in the brain.
In short, neural manifold is a low-dimensional structure, embedded in the high-dimensional state space of the neural network, where each axis represents the activity level of a single neuron. A neural manifold is often associated with a semantic meaning and is thus used in data analysis to measure the properties of semantic representation in the network.

Although many neural manifolds have been observed in experiments, a fundamental question is: are neural manifolds only a phenomena that we can observe, or it is associated with fundamental principles that govern the cognitive process in the brain?

In this blog, I give a few examples of neural manifolds revealed in the brain and further discuss a mathematical framework proposed by on how to view the cognitive process as evolution on neural manifolds and manifold restructuring. This framework, with further development, can potentially unleash the power of Riemann geometry to analytically reveal universal computational principles in the brain.

        Task                    Manifold                                                                        Observation
Nieh    Evidence accumulation   2D manifold jointly represent the spatial location and evidence quantity        Single cells tile the 2D manifold with firing field
        Left and right turn
Esparza back and forth running  1D ring manifold representing position of the animal in forward and bakwad run  After flip of the cooridor, the ring manifold represented in deep PCs flipped, while the one represented in superficual PCs kept its original direction
Sun     Cue-dependent reward delivery at near and far location

The stimulus in near and far context were step-by-step splitted into two rings with connection points only at the trial start and end

These findings lead us to the following conclusions:
1. Neural manifolds are observable.
2. Neural network state evolves as a trajectory on the neural manifold.
3. Neural manifolds undergo structural reorganization in different context or during learning.

With these observation, can we model the brain as a system that produces manifolds, travels along manifolds and restructure manifolds?
If so, how can we model such system?

After a discussion with Dr. Lu, who proposed a mathematical framework of intelligence in his arxiv paper, an initial idea was described.

In an autonomous intelligent system, an aprior low-dimensional manifold exists in the state space. Without any perturbation, the state of the system evolves along the geodesics of the manifold. The trajectory that the state of the system travels is defined as the thought flow.

When the system starts to accept input signals, the thought flow is pulled away from the trajectory by the unexpected input signal, namely prediction errors.

In the long term, the prediction error signals drive the change of the manifold structure, guiding the future thought low through new geodesics that better matches the outside environment.


Although more mathematical contents and simulation methods are needed to flesh up this framework, the idea is straightforward enough for further digestion.



As a neurobiologist, when faced with this new theoretical frame, I naturally ask, whether this is what happens in the brain?

Especially, how is the geometric structure encoded in the brain? Are these properties encoded in a specific brain region or are they distributely encoded?
How is the dynamcis on the manifold implemented with neural circuits?
How is manifold structure modified in process of learning?

Is the model of manifold only a different view on the system, compared to other classical models, e.g. network dynamics, or can this model bring some not easily generated by other models?
To be more specific, can Riemann and his decendents help us better understand the brain?

What experiments are required to confirm or falsify such view?

How much we can reveal with a linear corridor?