---
title: "Reward prediction context-dependent navigation"
date: 2026-01-28
categories: [modeling]
format: html
---
Since I joined CEBSIT in Shanghai, I have been participating in a weekly workshop on computational neuroscience. The workshop has a nice structure of first introducing basic computational neuroscience concepts and then encourage students and postdocs to try out those concepts on their own experimental data.

This blog is one of such attempts: I was analyzing recordings from hippocampal neurons as animals learn to navigate in a T-shaped maze in a context-dependent manner (Fig. 1). Context generally refers to a continuous diffusive set of sensory stimulus that spans a certain range of space and time, but here the context has narrowly defined to be a combination of visual stimuli that stretches along the middle range of the main track of the T-maze. In each trial, either context A or B was given and the animal learns to associate context A with turning left at the end of the main track, and B with turning right, in order to receive a reward.

TODO Figure 1

As I am almost clueless about how to analyze such dataset, I decide to try an angle learned from the workshop: the reward prediction error.

Briefly, the reward prediction error is a measure used in reinforcement that quantifies how much error an agent makes in predicting future reward. In the context of neuroscience, let's call the agent an "animal". At each time step $t$, the animal resides in a state $s_t$. Depending on the state, the animal receive a reward with its value given by $r_t$.  Hence, each possible state is associated with a so-called value $V(s_t)$, which is defined as:
$$V(s_t) = \mathbb{E}[\sum_{i=0}^{\infty}\gamma^i r_{t+1}]$$, the expectation of all the future reward, weighted by a power of a discount factor $\gamma$, depending on how far in the future the reward will be.

However, the ground-truth value function $V(s_t)$ defined in the environment is not directly accessible, it can only be estimated by the animal. To improve the estimation $\hat{V}(s_t)$ step by step, the animal can compare the current estimate $\hat{V}(s_t)$ and the estimate based on the current reward information $r_t + \gamma \hat{V}(s_t)$, which can be thought of as a "better" esitmation. The reward prediction error is thus the difference between the "prediction" $\hat{V}(s_t)$ and the "target" $r_t + \gamma \hat{V}(s_t)$:

TODO Equation figure 1 (RPE)

Although RPE is most commonly reported to be encoded in the dopaminergic system rather than the hippocampus, it does not prevent us from using this framework to understand how reward-association learning occurred. Before we can use this framework, another important factor needs to be added: the animal does not only estimate the future reward passively, but also take actions to increase the chance of getting a reward. For simplicity, the state $s_t$ of the animal is the location of the animal in the T-maze, and the action $a_t$ is sampled from $\{"forward", "left turn" and "right turn"\}$. Obviously, the choice of action $a$ depends on the state $s$, and this dependency is modeled as a conditional probability distribution $\pi (a|s)$.

Now our model has two parts: the action selection and the value estimation. This kind of model is called a actor-critic model in reinforcement learning, where the actor chooses actions and the critic evaluates them to guide learning and improve performance over time.

Boiling down to the model architecture, we need some output units to encode the action policy, which is the probability of taking each of the possible actions ($P_{forward}, P_{left}, P_{right}$). In addition, we need an output unit to encode the estimation of $V_t$. The input signal is a high dimensional vector, varying across spatial location and is context-specific. The latent layers include a recurrent neural network (CA3) feedforwardly connected to a single layer (CA1), which is a over-simplification of the hippocampus (Fig. 2).

TODO network structure

Environment


CA1 representation

reward prediction error
